[project]
name = "footycli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "blessed>=1.21.0",
    "dotenv>=0.9.9",
    "requests==2.32.4",
    "rich>=14.0.0",
    "schedule>=1.2.2",
    "textual>=3.7.1",
]
